# Generated by Django 5.2.14 on 2026-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('api_key_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('rate_limit', models.PositiveIntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
